using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;

// App name
[assembly: AssemblyTitle("Line Rider Overhaul")]

// App version
[assembly: AssemblyInformationalVersion("1.5.0.8b")]
// Note: AssemblyFileVersion and contents of "../version" are autogenerated from this value

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("f17a6235-b6bb-4ffe-b468-4fac1335dedf")]

// Custom fields generated during build process
namespace linerider
{
    [AttributeUsage(AttributeTargets.Assembly)]
    public class CustomAttributes(string subversion, string changelog) : Attribute
    {
        public string SubVersion { get; set; } = subversion.Trim().ToLower();
        public List<string> Changelog { get; set; } = [.. changelog.Replace("\r\n", "\n").Split('\n')];
    }
}