using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;

// App name
[assembly: AssemblyTitle("Line Rider Overhaul")]

// App version
// Note: AssemblyFileVersion and contents of "../version" is autogenerated from this value
[assembly: AssemblyInformationalVersion("1.5.0.7a")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("f17a6235-b6bb-4ffe-b468-4fac1335dedf")]

// Custom fields generated during build process
namespace linerider
{
    [AttributeUsage(AttributeTargets.Assembly)]
    public class CustomAttributes : Attribute
    {
        public string SubVersion { get; set; }
        public List<string> Changelog { get; set; }
        public CustomAttributes(string subversion, string changelog)
        {
            SubVersion = subversion.Trim().ToLower();
            Changelog = changelog.Replace("\r\n", "\n").Split('\n').ToList();
        }
    }
}